locations = [
    "Abū al Maţāmīr,Beheira,Egypt",
    "Ad-Damazin,Blue Nile,Sudan",
    "Agoura Hills,California,United States",
    "Al ‘Ayyāţ,Giza,Egypt",
    "Al Ḩasakah,Al-Hasakah,Syrian Arab Republic",
    "Alīpur,Delhi,India",
    "An Nuhūd,West Kordofan,Sudan",
    "Antananarivo,Analamanga,Madagascar",
    "Anxiang,Henan,China",
    "Arzamas,Nizhny Novgorod Oblast,Russian Federation",
    "Ascención de Guarayos, Plurinational State of Bolivia",
    "Ash Shafā,Mecca Region,Saudi Arabia",
    "Atakpamé,Plateaux,Togo",
    "Ataq,Shabwah,Yemen",
    "Avon Lake,Ohio,United States",
    "Bacchus Marsh,Victoria,Australia",
    "Bad Kreuznach,Rheinland-Pfalz,Germany",
    "Bagan Serai,Perak,Malaysia",
    "Bahau,Negeri Sembilan,Malaysia",
    "Bangangté,West,Cameroon",
    "Bāntva,Gujarat,India",
    "Bastia,Corsica,France",
    "Beihai,Guangxi,China",
    "Beitbridge,Matabeleland South Province,Zimbabwe",
    "Bekily,Androy,Madagascar",
    "Bekobod,Tashkent Region,Uzbekistan",
    "Berwick,Victoria,Australia",
    "Bhānder,Madhya Pradesh,India",
    "Bhātāra,Dhaka Division,Bangladesh",
    "Bhatkal,Karnataka,India",
    "Bhopal,Madhya Pradesh,India",
    "Bissāu,Rajasthan,India",
    "Bloomingdale,Illinois,United States",
    "Bogenhausen,Bavaria,Germany",
    "Bongaigaon,Assam,India",
    "Boshan,Shandong,China",
    "Bouna,Zanzan District,Côte d'Ivoire",
    "Brahmapur,Odisha,India",
    "Brasília,Federal District,Brazil",
    "Brezina,El Bayadh,Algeria",
    "Budva,Budva,Montenegro",
    "Bunbury,Western Australia,Australia",
    "Cacimba de Dentro,Paraiba,Brazil",
    "Çarşamba,Samsun,Türkiye",
    "Catbalogan,Eastern Visayas,Philippines",
    "Chaihe,Heilongjiang,China",
    "Chapadão do Sul,Mato Grosso do Sul,Brazil",
    "Chenghua,Guangdong,China",
    "Cheranmahadevi,Tamil Nadu,India",
    "Cheras,Selangor,Malaysia",
    "Chicago,Illinois,United States",
    "Chico,California,United States",
    "Chirkunda,Jharkhand,India",
    "Chūō,Yamanashi,Japan",
    "Ciriè,Piedmont,Italy",
    "Codlea,Brasov County,Romania",
    "Colombo,Western Province,Sri Lanka",
    "Comilla,Chittagong,Bangladesh",
    "Contramaestre,Santiago de Cuba Province,Cuba",
    "Culemborg,Gelderland,Netherlands",
    "Curug,Banten,Indonesia",
    "Dalian,Liaoning,China",
    "Dasheng,Shandong,China",
    "Degan,Chongqing,China",
    "Delmiro Gouveia,Alagoas,Brazil",
    "Dilijan,Tavush,Armenia",
    "Dingtao,Shandong,China",
    "Dohār,Dhaka Division,Bangladesh",
    "Dolores,Soriano,Uruguay",
    "Dongfeng,Jilin,China",
    "East Haven,Connecticut,United States",
    "Effium,Ebonyi State,Nigeria",
    "Estrela de Alagoas,Alagoas,Brazil",
    "‘Ewa Gentry,Hawaii,United States",
    "Farroupilha,Rio Grande do Sul,Brazil",
    "Fatehpur,Punjab,Pakistan",
    "Formosa,Formosa,Argentina",
    "Fuyang,Anhui,China",
    "Gasteiz / Vitoria,Basque Country,Spain",
    "Gikongoro,Southern Province,Rwanda",
    "Goudomp,Sedhiou,Senegal",
    "Grand Rapids,Michigan,United States",
    "Guarenas, Bolivarian Republic of Venezuela",
    "Gulou,Chongqing,China",
    "Gunnaur,Uttar Pradesh,India",
    "Guojia,Chongqing,China",
    "Halabja,Halabja,Iraq",
    "Hamina,Kymenlaakso,Finland",
    "Hejiang,Sichuan,China",
    "Hickory,North Carolina,United States",
    "Higuerote, Bolivarian Republic of Venezuela",
    "Hok Yuen,Kowloon City,Hong Kong",
    "Huangshi,Hubei,China",
    "Huber Heights,Ohio,United States",
    "Ikungi, United Republic of Tanzania",
    "Inokashira,Tokyo,Japan",
    "Iringa, United Republic of Tanzania",
    "Itaboraí,Rio de Janeiro,Brazil",
    "Itapoá,Santa Catarina,Brazil",
    "Jaguaruna,Santa Catarina,Brazil",
    "Jieshou,Anhui,China",
    "Jiuchi,Chongqing,China",
    "Kalaa Srira,Sousse Governorate,Tunisia",
    "Kallithéa,Attica,Greece",
    "Kamo,Niigata,Japan",
    "Karaçoban,Erzurum,Türkiye",
    "Karlovy Vary,Karlovarsky kraj,Czechia",
    "Karor,Punjab,Pakistan",
    "Kashmor,Sindh,Pakistan",
    "Kawage,Mie,Japan",
    "Kawardha,Chhattisgarh,India",
    "Kawit,Calabarzon,Philippines",
    "Keffi,Nasarawa State,Nigeria",
    "Kendari,Southeast Sulawesi,Indonesia",
    "Khalīlābād,Uttar Pradesh,India",
    "Kilosa, United Republic of Tanzania",
    "Kilwinning,Scotland,United Kingdom",
    "Kinel’-Cherkassy,Samara Oblast,Russian Federation",
    "Kırkağaç,Manisa,Türkiye",
    "Komagane,Nagano,Japan",
    "Kornwestheim,Baden-Wurttemberg,Germany",
    "Kosaya Gora,Tula Oblast,Russian Federation",
    "Kota Kinabalu,Sabah,Malaysia",
    "Kuangshi,Hebei,China",
    "Kurihama,Kanagawa,Japan",
    "Kurye, Republic of Korea",
    "Lahewa,North Sumatra,Indonesia",
    "Langgar,Xinjiang,China",
    "Laurel,Maryland,United States",
    "Le Camas,Provence-Alpes-Cote d'Azur,France",
    "Lee On,Sha Tin,Hong Kong",
    "Lengshuijiang,Hunan,China",
    "Lhokseumawe,Aceh,Indonesia",
    "Liberec,Liberecky kraj,Czechia",
    "Lintan Chengguanzhen,Gansu,China",
    "Littau,Lucerne,Switzerland",
    "Locarno,Ticino,Switzerland",
    "Loralai,Balochistan,Pakistan",
    "Lübeck,Schleswig-Holstein,Germany",
    "Macia,Gaza Province,Mozambique",
    "Mahē,Kerala,India",
    "Manokwari,West Papua,Indonesia",
    "Mayenne,Pays de la Loire,France",
    "Mbandjok,Centre,Cameroon",
    "Merta Road,Rajasthan,India",
    "Metemma,Amhara,Ethiopia",
    "Miano,Campania,Italy",
    "Moca,Espaillat Province,Dominican Republic",
    "Mödling,Lower Austria,Austria"
    "Molodohvardiisk,Luhansk,Ukraine",
    "Monterey Park,California,United States",
    "Morong,Calabarzon,Philippines",
    "Muchun,Sughd,Tajikistan",
    "Mu’er,Chongqing,China",
    "Nacala,Nampula,Mozambique",
    "Natick,Massachusetts,United States",
    "Naxi,Sichuan,China",
    "Netrakona,Mymensingh Division,Bangladesh",
    "Newtonbrook West,Ontario,Canada",
    "Nghi Sơn,Thanh Hoa Province,Viet Nam",
    "Nieuwegein,Utrecht,Netherlands",
    "Noida,Uttar Pradesh,India",
    "Novate Milanese,Lombardy,Italy",
    "Novocherkassk,Rostov,Russian Federation",
    "Novogrudok,Grodnenskaya,Belarus",
    "Novorossiysk,Krasnodar Krai,Russian Federation",
    "Nunukan,North Kalimantan,Indonesia",
    "Ocumare del Tuy, Bolivarian Republic of Venezuela",
    "Ōgi,Tokyo,Japan",
    "Okara,Punjab,Pakistan",
    "Oke Mesi,Osun State,Nigeria",
    "Oświęcim,Lesser Poland,Poland",
    "Otradnoye,Moscow,Russian Federation",
    "Ottweiler,Saarland,Germany",
    "Paramagudi,Tamil Nadu,India",
    "Paraopeba,Minas Gerais,Brazil",
    "Parvomay,Plovdiv,Bulgaria",
    "Pattukkottai,Tamil Nadu,India",
    "Pematangsiantar,North Sumatra,Indonesia",
    "Peoria,Illinois,United States",
    "Perris,California,United States",
    "Phnom Penh,Phnom Penh,Cambodia",
    "Phon Charoen,Nong Khai,Thailand",
    "Pinhal Novo,Setubal,Portugal",
    "Plettenberg,North Rhine-Westphalia,Germany",
    "Płońsk,Mazovia,Poland",
    "Plunge,Telsiai,Lithuania",
    "Poltava,Poltava,Ukraine",
    "Prey Veng,Prey Veng,Cambodia",
    "Pulwama,Jammu and Kashmir,India",
    "Puryŏng-ŭp, Democratic People's Republic of Korea",
    "Puthia,Rajshahi Division,Bangladesh",
    "Quiterianópolis,Ceara,Brazil",
    "Rancho Mirage,California,United States",
    "Río Cuarto,Cordoba,Argentina",
    "Rittenhouse,Pennsylvania,United States",
    "Robit,Amhara,Ethiopia",
    "Sa Dec,Dong Thap,Viet Nam",
    "Saint Andrews,Scotland,United Kingdom",
    "Saint Cloud,Florida,United States",
    "San Antonio,Valparaiso,Chile",
    "San Dimas,California,United States",
    "San Pedro Sula,Cortes Department,Honduras",
    "Santa Luzia,Minas Gerais,Brazil",
    "Sapé,Paraiba,Brazil",
    "Sayreville Junction,New Jersey,United States",
    "Sector 4,Bucuresti,Romania",
    "Silla,Valencia,Spain",
    "Sinkassé,Savanes,Togo",
    "Sirohi,Rajasthan,India",
    "Slough,England,United Kingdom",
    "Smithtown,New York,United States",
    "Snezhinsk,Chelyabinsk,Russian Federation",
    "Sonsón,Antioquia,Colombia",
    "Southaven,Mississippi,United States",
    "Sterling Heights,Michigan,United States",
    "Sumber,West Java,Indonesia",
    "Sun City,California,United States",
    "Ţahţā,Sohag,Egypt",
    "Taichung, Province of China Taiwan",
    "Taunton,England,United Kingdom",
    "Tema,Greater Accra,Ghana",
    "Tepecik,Istanbul,Türkiye",
    "Thái Bình,Hung Yen Province,Viet Nam",
    "Tindal,Tamil Nadu,India",
    "Tirorā,Maharashtra,India",
    "Toowoomba,Queensland,Australia",
    "Uglich,Yaroslavl Oblast,Russian Federation",
    "Union City,California,United States",
    "Universidad,Madrid,Spain",
    "Uxbridge,England,United Kingdom",
    "Valencia,Los Rios,Ecuador",
    "Vavatenina,Analanjirofo,Madagascar",
    "Vestal,New York,United States",
    "Ville-Émard,Quebec,Canada",
    "Vĩnh Yên,Phu Tho,Viet Nam",
    "Vsetín,Zlin,Czechia",
    "Wafangdian,Liaoning,China",
    "Wakimachi,Tokushima,Japan",
    "Warri,Delta,Nigeria",
    "Washwood Heath,England,United Kingdom",
    "Wednesbury,England,United Kingdom",
    "Wekiwa Springs,Florida,United States",
    "Wermelskirchen,North Rhine-Westphalia,Germany",
    "Westhoughton,England,United Kingdom",
    "Xiaochangshan,Liaoning,China",
    "Yebao,Gansu,China",
    "Zacualtipán,Hidalgo,Mexico",
    "Zhouxi,Guizhou,China"
]
